### ISSUE TITLE
Logo floating too far right

### ISSUE THREAD

**Issue by TienPhan** [Readify/telstra-purple-signatures#32]
### Styling Issue

Signature block should be fixed to 500px instead of 612px
![image](https://user-images.githubusercontent.com/2811255/65565735-2460fa80-df94-11e9-8f8e-17f155f3aff4.png)

### Comparison
Telstra Purple vs Telstra
![image](https://user-images.githubusercontent.com/2811255/65566129-4b6bfc00-df95-11e9-9739-950f397b4c95.png)

**Comment by robdmoore** [comment]
Fixed by #33
