### ISSUE TITLE
serialize-javascript

### ISSUE THREAD

**Issue by kjacobsen** [Readify/telstra-purple-signatures#44]
1 serialize-javascript vulnerability found in yarn.lock 3 days ago

## Remediation
Upgrade serialize-javascript to version 2.1.1 or later. For example:

```
serialize-javascript@^2.1.1:
  version "2.1.1"
```
Always verify the validity and compatibility of suggestions with your codebase.

## Details
GHSA-h9rv-jmmf-4pgx
moderate severity
Vulnerable versions: < 2.1.1
Patched version: 2.1.1
regular expressions Cross-Site Scripting (XSS) vulnerability
Impact
Affected versions of this package are vulnerable to Cross-site Scripting (XSS). It does not properly mitigate against unsafe characters in serialized regular expressions.

This vulnerability is not affected on Node.js environment since Node.js's implementation of RegExp.prototype.toString() backslash-escapes all forward slashes in regular expressions.

If serialized data of regular expression objects are used in an environment other than Node.js, it is affected by this vulnerability.

## Patches
This was patched in v2.1.1.

**Comment by kjacobsen** [comment]
Alert raised via Dependabot, but it isn't able to create an auto update due to dependencies.

**Comment by mderriey** [comment]
Closed in #57
