### ISSUE TITLE
Formatting Issue in Outlook for Mac

### ISSUE THREAD

**Issue by RobFaie** [Readify/telstra-purple-signatures#72]
I seem to be loosing a decent amount of the formatting when performing the copy paste into Outlook for Mac:

![image](https://user-images.githubusercontent.com/4196983/83377637-88886800-a419-11ea-8fc0-a44484776449.png)

Last time I updated my signature back in Nov '19 I did not have this issue. In addition, copying my signature from then out of OWA and pasting it into Outlook for Mac works fine which suggests something changed here in the signature app.

The behaviour is the same when copying from Edge, Brave, and Safari as well as pasting into other rich text editors like TextEdit and Word.

**Comment by kjacobsen** [comment]
Broken on Windows for me as well.

![image](https://user-images.githubusercontent.com/2404128/83601763-90c8da80-a5b4-11ea-9f8c-94262ecaeb89.png)

**Comment by robdmoore** [comment]
OK, something's broken. This was definitely working before. Someone needs to investigate :)

**Comment by AHoran** [comment]
> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-UWuiAvk2j2gLogVa/yisrcb38OIdGSJdP8onw4LmHzY='), or a nonce ('nonce-...') is required to enable inline execution.

At line 133 in index.js

**Comment by tonesandtones** [comment]
Another sample for Windows

Signature generator...
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/886113/83614114-56147180-a5b7-11ea-8b70-1b61a81b354c.png)

Copy by clicking the "Copy Signature" button
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/886113/83614108-54e34480-a5b7-11ea-8142-c539b6755059.png)

Copy by drag-select + ctrl+c
![image](https://user-images.githubusercontent.com/886113/83614397-bc00f900-a5b7-11ea-9bb5-3e2043d97458.png)

**Comment by robdmoore** [comment]
@AHoran ahh that'd do it. @mderriey looks like the security changes may have caused this then?

**Comment by robdmoore** [comment]
https://github.com/Readify/telstra-purple-signatures/blob/master/public/web.config#L38 <- if someone has time to resolve it's here

**Comment by mderriey** [comment]
On it, apologies!

**Comment by robdmoore** [comment]
All good, easy mistake.
